# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/pheno-utils',
                'doc_host': 'https://hrossman.github.io',
                'git_url': 'https://github.com/hrossman/pheno-utils',
                'lib_path': 'pheno_utils'},
  'syms': {'pheno_utils.core': {'pheno_utils.core.foo': ('core.html#foo', 'pheno_utils/core.py')}}}
